version: '3'
services: 
    master:
        image: wildfly/master
        ports: 
            - 9990:9990
        networks:
            cluster:
                ipv4_address: 192.168.1.10     
        volumes: 
            - ./data/master:/opt/jboss/wildfly/domain/configuration
               
    load-balancer:
        image: wildfly/load-balancer
        ports: 
            - 8080:8080
        depends_on: 
            - master
        networks:
            cluster:
                ipv4_address: 192.168.1.11           
    node1:
        image: wildfly/node
        depends_on: 
            - master
            - load-balancer
        networks:
            cluster:
                ipv4_address: 192.168.1.12
        environment: 
            - MASTER_IP=192.168.1.10
            - NODE_IP=192.168.1.12
        volumes: 
            - ./data/node1:/opt/jboss/wildfly/domain/configuration        
    node2:
        image: wildfly/node
        depends_on: 
            - master
            - load-balancer
        networks:
            cluster:
                ipv4_address: 192.168.1.13
        environment: 
            - MASTER_IP=192.168.1.10
            - NODE_IP=192.168.1.13      
        volumes: 
            - ./data/node2:/opt/jboss/wildfly/domain/configuration      
networks:
    cluster:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.1.0/24 
    