version: '3'
services: 
    master:
        image: wildfly-master
        ports: 
            - 9990:9990
    node1:
        image: wildfly-node1
        depends_on: 
            - master
        
    