version: '3'
services: 
    master:
        image: wildfly/master
        ports: 
            - 9990:9990
    load-balancer:
        image: wildfly/load-balancer
        depends_on: 
            - master
    node1:
        image: wildfly/node1
        depends_on: 
            - master
            - load-balancer
        
    